version: '3.8'  # Use the latest version of Compose

services:
  logstash:
    image: 6711/logstash3:1.0.0
    environment:
       REDIS_HOST : "localhost"
    entrypoint: ["/bin/bash", "/sub.sh"]
    # depends_on:
    #   - elastiksearch
  elastiksearch:
    image: 6711/elasticsearch
    entrypoint: ["/bin/bash", "/entry.sh"]
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: 6711/kibana
    # depends_on:
    #   - elastiksearch
    ports:
      - "5601:5601"
    